server:
  applicationConnectors:
    - type: http
      port: 8090
      bindHost: 127.0.0.1
database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: T3kn0s!123
  url: jdbc:mysql://localhost:3306/vis_vdj